Resources:
  MyDynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Status-Progress
      AttributeDefinitions:
        - AttributeName: Artist
          AttributeType: S
        - AttributeName: Singer
          AttributeType: S
      KeySchema:
        - AttributeName: Artist
          KeyType: HASH
        - AttributeName: Singer
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

